name = "FormationTemps"
uuid = "03bcd87b-2230-4045-a5fa-95a5fcdd1ff8"
authors = ["Michael Palumbo"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
